# Generated by Django 4.2.13 on 2025-12-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
