# Generated by Django 4.2.13 on 2024-07-25 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_alter_server_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='log_path',
        ),
        migrations.RemoveField(
            model_name='service',
            name='port',
        ),
    ]
