# Generated by Django 4.2.13 on 2024-07-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_remove_service_log_path_remove_service_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=15)),
                ('service', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=400)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
