# Generated by Django 4.2.13 on 2024-07-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_alter_logs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
